const images = {
  logo: require('../assets/images/logo.png'),
  background1: require('../assets/images/background1.png'),
  background2: require('../assets/images/background2.png'),
  background3: require('../assets/images/background3.png'),
  passwordshow: require('../assets/images/passwordshow.png'),
  backImage: require('../assets/images/backImage.png'),
  facebook: require('../assets/images/facebook.png'),
  apple: require('../assets/images/apple.png'),
  google: require('../assets/images/google.png'),
  downArrow: require('../assets/images/downArrow.png'),
  search: require('../assets/images/search.png'),
  dualipa: require('../assets/images/dualipa.png'),
  podcast1: require('../assets/images/podcast1.png'),
  notification: require('../assets/images/notification.png'),
  profile: require('../assets/images/profile.png'),
  boxes: require('../assets/images/boxes.png'),
  music: require('../assets/images/music.png'),
  podcast: require('../assets/images/podcast.png'),
  radio: require('../assets/images/radio.png'),
  audiobooks: require('../assets/images/audiobooks.png'),
  news: require('../assets/images/news.png'),
  album1: require('../assets/images/album1.png'),
  album2: require('../assets/images/album2.png'),
};

export default images;
