const images = {
  logo: require('../assets/images/logo.png'),
  background1: require('../assets/images/background1.png'),
  background2: require('../assets/images/background2.png'),
  background3: require('../assets/images/background3.png'),
  passwordshow: require('../assets/images/passwordshow.png'),
  backImage: require('../assets/images/backImage.png'),
  facebook: require('../assets/images/facebook.png'),
  apple: require('../assets/images/apple.png'),
  google: require('../assets/images/google.png'),
  downArrow: require('../assets/images/downArrow.png'),
  search: require('../assets/images/search.png'),
  notification: require('../assets/images/notification.png'),
  profile: require('../assets/images/profile.png'),
  boxes: require('../assets/images/boxes.png'),
  music: require('../assets/images/music.png'),
  podcast: require('../assets/images/podcast.png'),
  radio: require('../assets/images/radio.png'),
  audiobooks: require('../assets/images/audiobooks.png'),
  news: require('../assets/images/news.png'),
  album1: require('../assets/images/album1.png'),
  album2: require('../assets/images/album2.png'),
  album3: require('../assets/images/album3.png'),
  album4: require('../assets/images/album4.png'),
  album5: require('../assets/images/album5.png'),
  artist1: require('../assets/images/artist1.png'),
  artist2: require('../assets/images/artist2.png'),
  artist3: require('../assets/images/artist3.png'),
  artist4: require('../assets/images/artist4.png'),
  artist5: require('../assets/images/artist5.png'),
  artist6: require('../assets/images/artist6.png'),
  artist7: require('../assets/images/artist7.png'),
  artist8: require('../assets/images/artist8.png'),
  artist9: require('../assets/images/artist9.png'),
  artist10: require('../assets/images/artist10.png'),
  podcast1: require('../assets/images/podcast1.png'),
  podcast2: require('../assets/images/podcast2.png'),
  podcast3: require('../assets/images/podcast3.png'),
  podcast4: require('../assets/images/podcast4.png'),
  podcast5: require('../assets/images/podcast5.png'),
  podcast6: require('../assets/images/podcast6.png'),
  song1: require('../assets/images/song1.png'),
  song2: require('../assets/images/song2.png'),
  play: require('../assets/images/play.png'),
};

export default images;
